name: Accessibility
on: push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm ci
      - name: Run pa11y-ci tests
        run: npm run test-a11y
      - name: Read pa11y-ci test results
        id: pa11yci_results
        uses: juliangruber/read-file-action@v1
        with:
          path: pa11yci/pa11yci-results.txt
      - name: Check for pa11y-ci errors
        if: contains(steps.pa11yci_results.outputs.content, 'Errors in')
        run: |
          echo "::error::Accessibility errors were found."
          echo "${{ steps.pa11yci_results.outputs.content }}"
          exit 1
